### ISSUE TITLE
Weather icons are too small

### ISSUE THREAD

**Issue by Clans** [YohanBream/Weather#1]

**Comment by YohanBream** [comment]
Hi, @Clans 
I fixed the issue. Earlier, the weather icons were loader from OpenWeatherMap "in real time" using Picassa. So, there were some glitches with the height of list items because of relatively slow upload. Now all icons are saves in project's assets. Also all images now have strict height and width (48dp in the List and 2x in Details).
Thank you for your comment.

**Comment by Clans** [comment]
Just for you to know, to avoid such glitches you just need to set the specific width and height of the `ImageView` that will display your images.

**Comment by YohanBream** [comment]
Thanks.
